/**
 * Smart Notes production runtime launcher.
 * Used by the AV runtime (av-runtime.json) — not the dev-workspace gateway.
 *
 * Builds the Next.js bundle when sources are newer than the last build,
 * then starts server.js with NODE_ENV=production.
 */

const fs = require('fs');
const path = require('path');
const { spawnSync, spawn } = require('child_process');

process.title = 'smart-notes';
process.env.NODE_ENV = 'production';

const appDir = __dirname;
const buildIdPath = path.join(appDir, '.next', 'BUILD_ID');
const nextEnvPkg = path.join(appDir, 'node_modules', '@next', 'env', 'package.json');
const nextCli = path.join(appDir, 'node_modules', 'next', 'dist', 'bin', 'next');

const SKIP_DIRS = new Set(['.next', '.turbo', 'node_modules', 'vault', 'test-results']);

// Files regenerated by `postbuild` (generate-service-worker). Their mtime is
// always newer than .next/BUILD_ID after a successful build, so excluding
// them prevents an infinite "needs rebuild" loop on every production start.
const SKIP_FILES = new Set(['service-worker.js']);

function latestMtimeMs(target) {
  if (!fs.existsSync(target)) return 0;
  const st = fs.statSync(target);
  if (!st.isDirectory()) {
    if (SKIP_FILES.has(path.basename(target))) return 0;
    return st.mtimeMs;
  }
  // Intentionally ignore directory mtime — on Windows it bumps whenever any
  // child is written (including SKIP_FILES), which would defeat the skip.
  let latest = 0;
  for (const entry of fs.readdirSync(target, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    if (!entry.isDirectory() && SKIP_FILES.has(entry.name)) continue;
    latest = Math.max(latest, latestMtimeMs(path.join(target, entry.name)));
  }
  return latest;
}

function needsBuild() {
  if (!fs.existsSync(buildIdPath)) return true;
  const buildMtime = fs.statSync(buildIdPath).mtimeMs;
  const watched = [
    path.join(appDir, 'src'),
    path.join(appDir, 'public'),
    path.join(appDir, 'server.js'),
    path.join(appDir, 'package.json'),
    path.join(appDir, 'next.config.mjs')
  ];
  return watched.some((p) => latestMtimeMs(p) > buildMtime);
}

function ensureDeps() {
  if (!fs.existsSync(nextCli) || !fs.existsSync(nextEnvPkg)) {
    console.error('[smart-notes] Dependencies incomplete. Run: npm install');
    process.exit(1);
  }
}

function runBuild() {
  console.log('[smart-notes] Building production bundle...');
  const npmCmd = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  const result = spawnSync(npmCmd, ['run', 'build'], {
    cwd: appDir,
    env: process.env,
    stdio: 'inherit',
    windowsHide: true,
    shell: process.platform === 'win32'
  });
  if (result.status !== 0) process.exit(result.status || 1);
}

ensureDeps();

if (needsBuild()) {
  runBuild();
} else {
  console.log('[smart-notes] Using cached production build');
}

const child = spawn(process.execPath, [path.join(appDir, 'server.js')], {
  cwd: appDir,
  env: process.env,
  stdio: 'inherit',
  windowsHide: true
});

child.on('exit', (code) => process.exit(code ?? 0));
process.on('SIGTERM', () => child.kill('SIGTERM'));
process.on('SIGINT', () => child.kill('SIGINT'));
